export default {
  UPDATE_DATE: "UPDATE_DATE",
  GET_PREMIERES: "GET_PREMIERES",
  GET_PREMIERES_PENDING: "GET_PREMIERES_PENDING",
  GET_PREMIERES_FULFILLED: "GET_PREMIERES_FULFILLED",
  GET_PREMIERES_REJECTED: "GET_PREMIERES_REJECTED",
  
  //actions to next premieres:
  GET_NEXT_PREMIERES: "GET_NEXT_PREMIERES",
  GET_NEXT_PREMIERES_FULFILLED: "GET_NEXT_PREMIERES_FULFILLED",
  GET_NEXT_PREMIERES_PENDING: "GET_NEXT_PREMIERES_PENDING",
  GET_NEXT_PREMIERES_REJECTED: "GET_NEXT_PREMIERES_REJECTED",

  //actions to credits:
  GET_CREDITS: "GET_CREDITS",
  GET_CREDITS_FULFILLED: "GET_CREDITS_FULFILLED",
  GET_CREDITS_PENDING: "GET_CREDITS_PENDING",
  GET_CREDITS_REJECTED: "GET_CREDITS_REJECTED",

  //actions to details movie:
  GET_MOVIE_DETAILS: "GET_MOVIE_DETAILS",
  GET_MOVIE_DETAILS_FULFILLED: "GET_MOVIE_DETAILS_FULFILLED",
  GET_MOVIE_DETAILS_PENDING: "GET_MOVIE_DETAILS_PENDING",
  GET_MOVIE_DETAILS_REJECTED: "GET_MOVIE_DETAILS_REJECTED",

  //actions for search
  GET_SEARCH: "GET_SEARCH",
  GET_SEARCH_FULFILLED: "GET_SEARCH_FULFILLED",
  GET_SEARCH_PENDING: "GET_SEARCH_PENDING",
  GET_SEARCH_REJECTED: "GET_SEARCH_REJECTED",
  CLEAR_SEARCH: "CLEAR_SEARCH",

}